--Remap space as leader key
vim.keymap.set("n", " ", "<Nop>", { silent = true, remap = false })
vim.g.mapleader = " "
vim.g.maplocalleader = " "

require "user.notational-fzf-vim"
require "user.plugins"

require "user.alpha"
require "user.autocommands"
require "user.autopairs"
require "user.cmp"
require "user.colorscheme"
require "user.copilot"
require "user.commands"
require "user.comment"
require "user.diffview"
require "user.editorconfig"
require "user.gitsigns"
require "user.impatient"
require "user.indentline"
require "user.keymaps"
require "user.lsp-zero"
require "user.lualine"
require "user.nvim-code-action-menu"
require "user.nvim-tree"
require "user.null-ls"
require "user.options"
require "user.prettier"
require "user.project"
require "user.reach"
require "user.refactoring"
require "user.taboo"
require "user.telekasten-plugin"
require "user.telescope"
require "user.tmux-navigator"
require "user.toggleterm"
require "user.treesitter"
require "user.typescript-nvim"
require "user.vim-qf"
require "user.vim-test"
require "user.whichkey"

-- TODO: switch to new setup for lsp_installer
-- https://github.com/williamboman/nvim-lsp-installer/discussions/636
