require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.comment"
require "user.diffview"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
require "user.reach"
require "user.toggleterm"
require "user.telekasten-plugin"
require "user.taboo"
require "user.prettier"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.nvim-code-action-menu"
require "user.alpha"
require "user.whichkey"
require "user.vim-qf"
require "user.autocommands"
require "user.editorconfig"

-- TODO: switch to new setup for lsp_installer
-- https://github.com/williamboman/nvim-lsp-installer/discussions/636
-- require "user.lspconfigs
