prSections:
- title: Needs Review
  filters: is:open review-requested:@me repo:brandingbrand/shipyard repo:brandingbrand/flagship.db repo:brandingbrand/accounts
- title: No Reviews
  filters: is:open repo:brandingbrand/shipyard repo:brandingbrand/flagship.db repo:brandingbrnad/accounts review:none draft:false not-label:"Integrators"
- title: My Pull Requests
  filters: is:open author:@me
- title: Subscribed
  filters: is:open -author:@me repo:dlvhdr/gh-prs
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
