tap "adoptopenjdk/openjdk"
tap "buo/cask-upgrade"
tap "facebook/fb"
tap "github/gh"
tap "jesseduffield/lazydocker"
tap "jesseduffield/lazygit"
tap "jesseduffield/lazynpm"
tap "joerdav/xc"
tap "kt3k/tap"
tap "mobile-dev-inc/tap"
tap "oven-sh/bun"
tap "withgraphite/tap"
# General-purpose data compression with high compression ratio
brew "xz"
# Color management engine supporting ICC profiles
brew "little-cms2"
# Image format providing lossless and lossy compression for web images
brew "webp"
# New file format for still image compression
brew "jpeg-xl"
# Codec library for encoding and decoding AV1 video streams
brew "aom"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Parser generator
brew "bison"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Core application library for C
brew "glib"
# Vector graphics library with cross-device output support
brew "cairo"
# Cross-platform make
brew "cmake"
# YAML Parser
brew "libyaml"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Dependency manager for Cocoa projects
brew "cocoapods"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Collection of reusable C++ library artifacts developed at Facebook
brew "folly"
# C++14 implementation of the TLS-1.3 standard
brew "fizz"
# Modular, composable client/server abstractions framework
brew "wangle"
# Facebook's branch of Apache Thrift, including a new C++ server
brew "fbthrift"
# Thrift functions for querying information from a service
brew "fb303"
# Shared library for Watchman and Eden projects
brew "edencommon"
# General purpose Language Server
brew "efm-langserver"
# Soft fork of the helix editor
brew "evil-helix"
# Easiest way to build and release mobile apps
brew "fastlane"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU database manager
brew "gdbm"
# Toolkit for image loading and pixel buffer manipulation
brew "gdk-pixbuf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Render markdown on the CLI
brew "glow"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# Generic library support script
brew "libtool"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# OpenType text shaping engine
brew "harfbuzz"
# Improved top (interactive process viewer)
brew "htop"
# Database of common MIME types
brew "shared-mime-info"
# ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
brew "libheif"
# C/C++ seam carving library
brew "liblqr"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Portable Foreign Function Interface library
brew "libffi"
# Package manager for the Lua programming language
brew "luarocks"
# Utility for directing compilation
brew "make"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# QUIC transport protocol implementation
brew "mvfst"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP/2 C Library
brew "nghttp2"
# Selects the right Node package manager based on lockfiles
brew "ni"
# Small build system for use with gyp or CMake
brew "ninja"
# Manage multiple Node.js versions
brew "nvm"
# Framework for layout and rendering of i18n text
brew "pango"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Object-relational database system
brew "postgresql@14"
# Python version management
brew "pyenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# File browser
brew "ranger"
# Ruby version manager
brew "rbenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Readline wrapper: adds readline support to tools that lack it
brew "rlwrap"
# Install Ruby, JRuby, Rubinius, TruffleRuby, or mruby
brew "ruby-install"
# Powerful, clean, object-oriented scripting language
brew "ruby@3.1"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Terminal based presentation tool
brew "slides"
# Cross-shell prompt for astronauts
brew "starship"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Opinionated Lua code formatter
brew "stylua"
# Tool Command Language
brew "tcl-tk"
# Code-search similar to ack
brew "the_silver_searcher"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash", link: true
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Watch files and take action when they change
brew "watchman"
# Internet file retriever
brew "wget"
# HTTP benchmarking tool
brew "wrk"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# Enable Windows-like alt-tab
cask "alt-tab"
# Transfer files from and to an Android smartphone
cask "android-file-transfer"
# Tools for building Android applications
cask "android-studio"
# Tool to replace abbreviations while typing
cask "atext"
# Control USB Cameras from an app
cask "cameracontroller"
# Universal database tool and SQL client
cask "dbeaver-community"
# App to build and share containerised applications and microservices
cask "docker-desktop"
# Client for the Dropbox cloud storage service
cask "dropbox"
cask "font-cascadia-code"
cask "font-cascadia-mono"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-nerd-font"
cask "font-go-mono-nerd-font"
cask "font-hack-nerd-font"
cask "font-heavy-data-nerd-font"
cask "font-inconsolata-go-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-iosevka"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-maple-mono-nf"
cask "font-meslo-lg-nerd-font"
cask "font-noto-nerd-font"
cask "font-roboto-mono-nerd-font"
cask "font-terminess-ttf-nerd-font"
cask "font-victor-mono"
cask "font-victor-mono-nerd-font"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Automation software
cask "keyboard-maestro"
# Visual diff and merge tool
cask "meld"
# Create mock APIs in seconds
cask "mockoon"
# Visual tool to design, develop and administer MySQL servers
cask "mysqlworkbench"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Control your tools with a few keystrokes
cask "raycast"
# Standalone app for debugging React Native apps
cask "react-native-debugger"
# Desktop app for inspecting React JS and React Native projects
cask "reactotron"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Note Taking: Nimble, Calm, Plain.txt
cask "the-archive"
# Open-source code editor
cask "visual-studio-code"
# OpenJDK distribution from Azul
cask "zulu@17"
vscode "4ops.terraform"
vscode "azemoh.one-monokai"
vscode "bodil.file-browser"
vscode "bradlc.vscode-tailwindcss"
vscode "brittanychiang.halcyon-vscode"
vscode "dahong.theme-bear"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "dsznajder.es7-react-js-snippets"
vscode "dunstontc.vscode-go-syntax"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "esbenp.prettier-vscode"
vscode "eserozvataf.one-dark-pro-monokai-darker"
vscode "formulahendry.auto-rename-tag"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "harryhopkinson.vim-theme"
vscode "jacobdufault.fuzzy-search"
vscode "jprestidge.theme-material-theme"
vscode "kahole.magit"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-pyright.pyright"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.vscode-typescript-next"
vscode "planbcoding.vscode-react-refactor"
vscode "vscodevim.vim"
vscode "vspacecode.vspacecode"
vscode "vspacecode.whichkey"
vscode "yoavbls.pretty-ts-errors"
vscode "zhuangtongfa.material-theme"
npm "@blowmage/cursor-agent-acp"
npm "corepack"
