-- return {
--   "AstroNvim/astrolsp",
--   ---@type AstroLSPOpts
--   opts = {
--     formatting = {
--       disabled = {
--         "prettierd",
--         "vtsls",
--         "eslint",
--         "tsserver",
--       },
--     },
--   },
-- }
